### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by makato-private** [HamzaAnis/go-spotify-account-generator#1]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x119dcf9]

goroutine 10 [running]:
github.com/HamzaAnis/go-spotify-account-generator/pkg/utils.MakeRequest({0xc00010a0e0, 0xc}, {0xc0001021b0, 0xf})
        C:/Users/marij/go/pkg/mod/github.com/!hamza!anis/go-spotify-account-generator@v0.0.0-20210919200237-bf60701e632b/pkg/utils/utils.go:31 +0x319
github.com/HamzaAnis/go-spotify-account-generator/pkg/spotify.CreateAccount()
        C:/Users/marij/go/pkg/mod/github.com/!hamza!anis/go-spotify-account-generator@v0.0.0-20210919200237-bf60701e632b/pkg/spotify/spotify.go:14 +0x9d
github.com/HamzaAnis/go-spotify-account-generator/cmd.Start.func1()
        C:/Users/marij/go/pkg/mod/github.com/!hamza!anis/go-spotify-account-generator@v0.0.0-20210919200237-bf60701e632b/cmd/cmd.go:23 +0x6c
created by github.com/HamzaAnis/go-spotify-account-generator/cmd.Start
        C:/Users/marij/go/pkg/mod/github.com/!hamza!anis/go-spotify-account-generator@v0.0.0-20210919200237-bf60701e632b/cmd/cmd.go:20 +0x125
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x119dcf9]

goroutine 6 [running]:
github.com/HamzaAnis/go-spotify-account-generator/pkg/utils.MakeRequest({0xc00010a040, 0xc}, {0xc000102048, 0xf})
        C:/Users/marij/go/pkg/mod/github.com/!hamza!anis/go-spotify-account-generator@v0.0.0-20210919200237-bf60701e632b/pkg/utils/utils.go:31 +0x319
github.com/HamzaAnis/go-spotify-account-generator/pkg/spotify.CreateAccount()
        C:/Users/marij/go/pkg/mod/github.com/!hamza!anis/go-spotify-account-generator@v0.0.0-20210919200237-bf60701e632b/pkg/spotify/spotify.go:14 +0x9d
github.com/HamzaAnis/go-spotify-account-generator/cmd.Start.func1()
        C:/Users/marij/go/pkg/mod/github.com/!hamza!anis/go-spotify-account-generator@v0.0.0-20210919200237-bf60701e632b/cmd/cmd.go:23 +0x6c
created by github.com/HamzaAnis/go-spotify-account-generator/cmd.Start
        C:/Users/marij/go/pkg/mod/github.com/!hamza!anis/go-spotify-account-generator@v0.0.0-20210919200237-bf60701e632b/cmd/cmd.go:20 +0x125
```

**Comment by HamzaAnis** [comment]
Please share the command you ran for it?

**Comment by HamzaAnis** [comment]
Closing because it is stale.
